### ISSUE TITLE
the function `define-error' is not known to be defined

### ISSUE THREAD

**Issue by futurist** [doublep/datetime#1]
```
Leaving directory `/root/.emacs.d/elpa/datetime-20161007.1137'
^L
Compiling file /root/.emacs.d/elpa/datetime-20161007.1137/datetime-pkg.el at Sat Mar 18 0\
8:03:09 2017
Entering directory `/root/.emacs.d/elpa/datetime-20161007.1137/'
^L
Compiling file /root/.emacs.d/elpa/datetime-20161007.1137/datetime.el at Sat Mar 18 08:03\
:09 2017

In end of data:
datetime.el:1235:1:Warning: the function `define-error' is not known to be
    defined.
```

What's this problem?

> GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-08 on lamiak, modi\
fied by Debian

**Comment by doublep** [comment]
Thank you, done as suggested on the linked page.

Note however, that the library is currently barely useful. The only implemented functionality is matching, since that's all that's currently needed by Logview.
