### ISSUE TITLE
Wrong number of arguments define-obsolete-function-alias

### ISSUE THREAD

**Issue by peterpaul** [doublep/datetime#4]
I'm playing around with the nativecomp branch of emacs, and I received a `(wrong-number-of-arguments (3 . 4) 2)` error on line 1524:

```
(define-obsolete-function-alias 'datetime-pattern-includes-millisecond-p 'datetime-pattern-includes-second-fractionals-p)
```
I reviewed the git commit log, and I believe this should be replaced by the following line:

```
(define-obsolete-function-alias 'datetime-pattern-includes-millisecond-p 'datetime-pattern-includes-second-fractionals-p "0.6.1")
```

**Comment by doublep** [comment]
Fixed in 0.7, thank you.
