### ISSUE TITLE
FYI: datetime-format library

### ISSUE THREAD

**Issue by alphapapa** [doublep/datetime#5]
This doesn't necessarily conflict with your library, but in case you ever wanted to add a `datetime-format` function...  :)  Just thought you should be aware.

https://github.com/emacs-php/emacs-datetime

**Comment by doublep** [comment]
Thank you, I saw it. Actually, my library exists only for Logview (no-one else uses it as far as I know), and in Logview I don't even use formatting, only other features `datetime` provides.

FWIW, `datetime` is faster.

    (timeit (dotimes (k 100000) (format-time-string "%Y-%m-%d %H:%m:%s" k)))
    ==> 1.13 s

    (let ((fmt (datetime-float-formatter 'java "yyyy-MM-dd HH:mm:ss")))
      (timeit (dotimes (k 100000) (funcall fmt k))))
    ==> 0.63 s
